In [2]:
import numpy as np

In [4]:
n = np.array([1,2,3])
print(n)
print(np.arange(5))

[1 2 3]
[0 1 2 3 4]


In [5]:
l = range(10000)
%timeit [i**3 for i in l]

1.2 ms ± 39.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
n = np.arange(10000)
%timeit n**3

31.7 µs ± 2.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
# matrix multiplication
p = np.diag([1,2,3])
print(p.dot(p))
print('\n')
print(p*p)

[[1 0 0]
 [0 4 0]
 [0 0 9]]


[[1 0 0]
 [0 4 0]
 [0 0 9]]


In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,0,0],[1,0,0],[0,1,0]])
print(np.matmul(a,b))
print('*********')
print(np.dot(a,b))
print('*********')
print(a*b)

[[ 3  3  0]
 [ 9  6  0]
 [15  9  0]]
*********
[[ 3  3  0]
 [ 9  6  0]
 [15  9  0]]
*********
[[1 0 0]
 [4 0 0]
 [0 8 0]]


In [22]:
l = np.array([1,2,3])
print(np.sum(l))
print(np.min(l))
print(np.argmin(l))

6
1
0


In [24]:
l = np.array([1,2,3,4,100])
print(np.mean(l))
print(np.median(l))

22.0
3.0


In [25]:
l2 = np.array([[1,2,3],[5,6,2]])
print(np.median(l2,axis=0))
print(np.median(l2,axis=1))
print(np.median(l2,axis=-1))

[3.  4.  2.5]
[2. 5.]
[2. 5.]


In [30]:
data = np.array([[1,20,100],[2,15,123],[3,23,143]])
srno, data1, data2 = data.T
print(data)
print('******')
print(data.T)

[[  1  20 100]
 [  2  15 123]
 [  3  23 143]]
******
[[  1   2   3]
 [ 20  15  23]
 [100 123 143]]


In [31]:
print(data)
print(srno)
print(data1)

[[  1  20 100]
 [  2  15 123]
 [  3  23 143]]
[1 2 3]
[20 15 23]


In [41]:
data2 = data[:,1:]
print(data2)
print(data2)

[[ 17 100]
 [ 15 123]
 [ 23 143]]
[[ 17 100]
 [ 15 123]
 [ 23 143]]


In [42]:
print(data)

[[  1  17 100]
 [  2  15 123]
 [  3  23 143]]


In [45]:
n = np.array([[1,2,3],[4,5,6]])
n.ravel()

array([1, 2, 3, 4, 5, 6])

In [47]:
n.T
n.T.ravel()

array([1, 4, 2, 5, 3, 6])